services:
  - type: web
    name: nuibe-web
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm run start-server
    autoDeploy: true

  - type: worker
    name: nuibe-bot
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm run start-bot
    autoDeploy: true
